integrated_storage:
    resolver:
        integrated:
            public: '/files'

integrated_content:
    mailer_from: '%env(resolve:mailer_from)%'
    mailer_name: '%env(resolve:mailer_name)%'

integrated_user:
    mailer_from: '%env(resolve:mailer_from)%'
    mailer_name: '%env(resolve:mailer_name)%'

integrated_solr:
    endpoints:
        default:
            host: '%env(resolve:SOLR_HOST)%'
            port: '%env(resolve:SOLR_PORT)%'
            username: '%env(resolve:SOLR_USERNAME)%'
            password: '%env(resolve:SOLR_PASSWORD)%'
            core: '%env(resolve:SOLR_CORE)%'
            timeout: '%env(resolve:SOLR_TIMEOUT)%'

integrated_social:
    facebook:
        app_id: '%env(resolve:FACEBOOK_APP_ID)%'
        app_secret: '%env(resolve:FACEBOOK_APP_SECRET)%'
    twitter:
        consumer_key: '%env(resolve:TWITTER_CONSUMER_KEY)%'
        consumer_secret: '%env(resolve:TWITTER_CONSUMER_SECRET)%'
