security:
    encoders:
        Integrated\Bundle\UserBundle\Model\User: bcrypt

    providers:
        integrated_user:
            id: integrated_user.security.provider

    firewalls:
        dev:
            pattern: ^(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern: ^/
            form_login:
                login_path:     integrated_user_login
                check_path:     integrated_user_check
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   integrated_user_logout
                target: /
            remember_me:
                secret:     "%kernel.secret%"
                lifetime:   2592000 # 30 days
                path:       /
            anonymous: ~
            logout_on_user_change: true
            scope: ~

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: [ IS_AUTHENTICATED_REMEMBERED, ROLE_SCOPE_INTEGRATED ] }

    access_decision_manager:
        strategy: unanimous
