version: '3'

services:
    apache:
        container_name: integrated-apache
        build: docker/apache
        volumes:
            - '.:/docker:cached'
        ports:
            - '80:80'

    mysql:
        container_name: integrated-mysql
        image: mysql:5.7
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker

    mongo:
        container_name: integrated-mongo
        image: 'mongo:3.4'
        ports:
            - '27017:27017'

    phpmyadmin:
        container_name: integrated-phpmyadmin
        image: 'phpmyadmin/phpmyadmin:4.7'
        ports:
          - '8080:80'
        environment:
            PMA_HOST: mysql
