version: '3'

services:
    apache:
        container_name: apache
        build: docker/apache
        volumes:
            - '.:/docker:cached'
        ports:
            - '80:80'
    mysql:
        container_name: mysql
        build: docker/mysql
        ports:
            - '3306:3306'
    mongodb:
        container_name: mongodb
        image: 'mongo:3.4'
        ports:
            - '27017:27017'
