integrated:
    resource: "@IntegratedIntegratedBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_website:
    resource: "@IntegratedIntegratedBundle/Resources/config/routing.website.xml"
    prefix: "/"
