default:
    extensions:
        Behat\MinkExtension:
            base_url: "http://localhost:8080/"
            default_session: symfony
            #files_path: "%paths.base%/src/Behat/Resources/fixtures/"
            sessions:
                symfony:
                    symfony: ~

        FriendsOfBehat\SymfonyExtension:
            kernel:
                bootstrap: vendor/autoload.php

        FriendsOfBehat\ContextServiceExtension:
            imports:
                - "src/Behat/Resources/config/services.xml"

        FriendsOfBehat\CrossContainerExtension: ~