integrated_block:
    resource: "@IntegratedBlockBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_page:
    resource: "@IntegratedPageBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_content:
    resource: "@IntegratedContentBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_user:
    resource: "@IntegratedUserBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_security:
    resource: "@IntegratedUserBundle/Resources/config/routing.security.xml"
    prefix: "/admin"

integrated_channel:
    resource: "@IntegratedChannelBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_workflow:
    resource: "@IntegratedWorkflowBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_content_history:
    resource: "@IntegratedContentHistoryBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_storage:
    resource: "@IntegratedStorageBundle/Resources/config/routing/storage.xml"
    prefix: "/"

integrated_website:
    resource: "@IntegratedWebsiteBundle/Resources/config/routing.xml"

integrated_theme:
    resource: "@IntegratedThemeBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_comment:
    resource: "@IntegratedCommentBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_sitemap:
    resource: "@IntegratedSitemapBundle/Resources/config/routing.xml"
