# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Integrated\Bundle\UserBundle\Model\User: bcrypt

    providers:
        integrated_user:
            id: integrated_user.security.provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern:  ^/
            form_login:
                login_path:    integrated_user_login
                check_path:    integrated_user_check
                csrf_token_generator: security.csrf.token_manager
                remember_me: true
            logout:
                path:   integrated_user_logout
                target: /
            remember_me:
                secret:   '%secret%'
                lifetime: 2592000 # 30 days
                path:     /
            anonymous: ~
            logout_on_user_change: true

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: IS_AUTHENTICATED_REMEMBERED }

    access_decision_manager:
        strategy: unanimous
