default:
    suites:
        connector:
            contexts:
                - integrated.behat.context.hook.doctrine_orm_context

                - integrated.behat.context.setup.admin
                - integrated.behat.context.setup.content
                - integrated.behat.context.setup.connector

                - integrated.behat.context.ui.admin.managing_connector_context
            filters:
                tags: "@connector"
