<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MongoDBBundle\DoctrineMongoDBBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    AntiMattr\Bundle\MongoDBMigrationsBundle\MongoDBMigrationsBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Knp\Bundle\PaginatorBundle\KnpPaginatorBundle::class => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
    Knp\Bundle\GaufretteBundle\KnpGaufretteBundle::class => ['all' => true],
    Gregwar\ImageBundle\GregwarImageBundle::class => ['all' => true],
    Integrated\Bundle\AssetBundle\IntegratedAssetBundle::class => ['all' => true],
    Integrated\Bundle\ContentBundle\IntegratedContentBundle::class => ['all' => true],
    Integrated\Bundle\FormTypeBundle\IntegratedFormTypeBundle::class => ['all' => true],
    Integrated\Bundle\IntegratedBundle\IntegratedIntegratedBundle::class => ['all' => true],
    Integrated\Bundle\SolrBundle\IntegratedSolrBundle::class => ['all' => true],
    Integrated\Bundle\StorageBundle\IntegratedStorageBundle::class => ['all' => true],
    Integrated\Bundle\UserBundle\IntegratedUserBundle::class => ['all' => true],
    Integrated\Bundle\LockingBundle\IntegratedLockingBundle::class => ['all' => true],
    Integrated\Bundle\SlugBundle\IntegratedSlugBundle::class => ['all' => true],
    Integrated\Bundle\ThemeBundle\IntegratedThemeBundle::class => ['all' => true],
    Integrated\Bundle\PageBundle\IntegratedPageBundle::class => ['all' => true],
    Integrated\Bundle\BlockBundle\IntegratedBlockBundle::class => ['all' => true],
    Integrated\Bundle\ChannelBundle\IntegratedChannelBundle::class => ['all' => true],
    Integrated\Bundle\WebsiteBundle\IntegratedWebsiteBundle::class => ['all' => true],
    Integrated\Bundle\MenuBundle\IntegratedMenuBundle::class => ['all' => true],
    Integrated\Bundle\WorkflowBundle\IntegratedWorkflowBundle::class => ['all' => true],
    Integrated\Bundle\ContentHistoryBundle\IntegratedContentHistoryBundle::class => ['all' => true],
    Integrated\Bundle\ImageBundle\IntegratedImageBundle::class => ['all' => true],
    Integrated\Bundle\CommentBundle\IntegratedCommentBundle::class => ['all' => true],
    Integrated\Bundle\InstallerBundle\IntegratedInstallerBundle::class => ['all' => true],
    Integrated\Bundle\ThompsonThemeBundle\IntegratedThompsonThemeBundle::class => ['all' => true],
    Integrated\Bundle\SitemapBundle\IntegratedSitemapBundle::class => ['all' => true],
    Integrated\Bundle\SocialBundle\IntegratedSocialBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true],
    Nelmio\Alice\Bridge\Symfony\NelmioAliceBundle::class => ['dev' => true, 'test' => true],
    Endroid\QrCodeBundle\EndroidQrCodeBundle::class => ['all' => true],
    Scheb\TwoFactorBundle\SchebTwoFactorBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    EWZ\Bundle\RecaptchaBundle\EWZRecaptchaBundle::class => ['all' => true],
];
